<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Configurations>Debug;Release;GitHub</Configurations>
    <ApplicationIcon>Resouces\pickaxe.ico</ApplicationIcon>
    <Authors>lyndychivs</Authors>
    <Product>Test Miner</Product>
    <Description>Test Miner for scraping NUnit3 Test Reports into a Database.</Description>
    <PackageProjectUrl>https://github.com/lyndychivs/TestMiner</PackageProjectUrl>
    <PackageIcon>pickaxe.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/lyndychivs/TestMiner</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>test;miner;unit;nunit;database;history;upload;record;testing</PackageTags>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Resouces\pickaxe.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resouces\pickaxe.ico" />
    <EmbeddedResource Include="Resouces\pickaxe.png">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TestMiner\TestMiner.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resouces\pickaxe.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>