<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <ApplicationIcon>Resources\pickaxe.ico</ApplicationIcon>
        <PackageIcon>pickaxe.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\pickaxe.ico" />
        <EmbeddedResource Include="Resources\pickaxe.png">
            <PackagePath>\</PackagePath>
            <Pack>True</Pack>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.Sinks.RichTextBox.WinForms.Colored" />
        <PackageReference Include="StyleCop.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TestMiner\TestMiner.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
