<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Resouces\pickaxe.ico</ApplicationIcon>
    <Title>Test Miner</Title>
    <Authors>lyndychivs</Authors>
    <Company>lyndychivs</Company>
    <PackageProjectUrl>https://github.com/lyndychivs/TestMiner</PackageProjectUrl>
    <PackageIcon>pickaxe.png</PackageIcon>
    <RepositoryUrl>https://github.com/lyndychivs/TestMiner</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>en</NeutralLanguage>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <PublishAot>False</PublishAot>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Description>Test Miner for scraping NUnit3 Test Reports into a Database.</Description>
    <Copyright>MIT</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>test;miner;unit;nunit;database;history;upload;record;testing</PackageTags>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <Configurations>Debug;Release;GitHub</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='GitHub|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <DebugType>none</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resouces\pickaxe.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resouces\pickaxe.ico" />
    <EmbeddedResource Include="Resouces\pickaxe.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TestMiner.Models\TestMiner.Models.csproj" />
    <ProjectReference Include="..\TestMiner.TestReports\TestMiner.TestReports.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Connection.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
</Project>