name: Build & Test
run-name: Build & Test
permissions:
    contents: read
    checks: write
    pull-requests: write
on:
    push:
    schedule:
        - cron: "0 4 * * SUN"
jobs:
    build-test:
        runs-on: ubuntu-latest
        env:
            CONFIGURATION: GitHub
            TARGET_FRAMEWORK: net8.0
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: Install .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 8.0.x

            - name: Restore
              run: dotnet restore

            - name: Build
              id: build
              run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}

            - name: Test
              if: steps.build.outcome == 'success'
              run: dotnet test --no-build --configuration ${{ env.CONFIGURATION }} --logger "trx;LogFileName=Test.Results.trx"

            - name: Publish All Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              if: (!cancelled())
              with:
                  files: "**/*.trx"
                  action_fail_on_inconclusive: true
