name: dotnet-restore-build-test
run-name: .NET Restore, Build, Test
permissions:
  contents: read
on:
  push:
  schedule:
    - cron: '0 4 * * SUN'
jobs:
  dotnet-restore-build-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --no-restore --configuration GitHub

    - name: dotnet test
      run: dotnet test --no-build --configuration GitHub --verbosity normal --list-tests --blame
